"""
Keeps src/pluginRegistry.jsx in sync with src/plugins.manifest.json.

src/plugins.manifest.json is the single source of truth for which UI
plugins exist (id, component name, file). pluginRegistry.jsx is *generated*
from it - nothing should ever hand-edit that file, because a small typo in
generated JSX (a stray comma, a duplicate key) breaks the whole frontend
build. Structured JSON is easy and safe to edit programmatically (by the
plugin importer, or by hand); regenerating the JSX from a template means
that file is always syntactically valid by construction.

Usage:
    python backend/plugin_tools/registry_sync.py

Or import and call regenerate_registry() from the plugin importer after it
adds a new entry to the manifest.
"""

import json
from pathlib import Path

# backend/plugin_tools/registry_sync.py -> repo root is two levels up
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MANIFEST_PATH = REPO_ROOT / "src" / "plugins.manifest.json"
REGISTRY_PATH = REPO_ROOT / "src" / "pluginRegistry.jsx"

_HEADER = (
    "// AUTO-GENERATED by backend/plugin_tools/registry_sync.py\n"
    "// Do not hand-edit this file - edit src/plugins.manifest.json instead,\n"
    "// then re-run: python backend/plugin_tools/registry_sync.py\n"
)


def load_manifest() -> list[dict]:
    if not MANIFEST_PATH.exists():
        return []
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save_manifest(entries: list[dict]) -> None:
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=4)
        f.write("\n")


def add_plugin_entry(plugin_id: str, component: str, file: str) -> list[dict]:
    """Adds (or replaces, if the id already exists) one entry in the
    manifest and returns the updated list. Does not write pluginRegistry.jsx
    itself - call regenerate_registry() after, or rely on the caller doing
    both together."""
    entries = load_manifest()
    entries = [e for e in entries if e["id"] != plugin_id]
    entries.append({"id": plugin_id, "component": component, "file": file})
    save_manifest(entries)
    return entries


def remove_plugin_entry(plugin_id: str) -> list[dict]:
    entries = [e for e in load_manifest() if e["id"] != plugin_id]
    save_manifest(entries)
    return entries


def _render_registry_jsx(entries: list[dict]) -> str:
    imports = "\n".join(
        f"import {e['component']} from './components/{e['file']}';" for e in entries
    )
    map_lines = "\n".join(f"    {e['id']}: {e['component']}," for e in entries)

    return (
        f"{_HEADER}\n"
        f"{imports}\n\n"
        f"// Registry of all available UI plugins\n"
        f"export const UI_PLUGINS = {{\n"
        f"{map_lines}\n"
        f"}};\n"
    )


def regenerate_registry() -> str:
    """Reads the manifest and rewrites pluginRegistry.jsx from scratch.
    Returns the generated source (mostly useful for tests)."""
    entries = load_manifest()
    source = _render_registry_jsx(entries)
    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        f.write(source)
    print(f"[registry_sync] Wrote {REGISTRY_PATH} with {len(entries)} plugin(s).")
    return source


if __name__ == "__main__":
    regenerate_registry()
