// AUTO-GENERATED by backend/plugin_tools/registry_sync.py
// Do not hand-edit this file - edit src/plugins.manifest.json instead,
// then re-run: python backend/plugin_tools/registry_sync.py

import MusicWindow from './components/MusicWindow.jsx';
import CadWindow from './components/CadWindow.jsx';
import KasaWindow from './components/KasaWindow.jsx';
import DoorWindow from './components/DoorWindow.jsx';
import PrinterWindow from './components/PrinterWindow.jsx';
import BrowserWindow from './components/BrowserWindow.jsx';
import ChessWindow from './components/ChessWindow.jsx';

// Registry of all available UI plugins
export const UI_PLUGINS = {
    music: MusicWindow,
    cad: CadWindow,
    kasa: KasaWindow,
    door: DoorWindow,
    printer: PrinterWindow,
    browser: BrowserWindow,
    chess: ChessWindow,
};
